### ISSUE TITLE
This is too complicated

### ISSUE THREAD

**Issue by Sneffel** [rene78/batch-convert-to-webp#2]
There is no way you thought this was user-friendly in the slightest. I know we're supposed to be completely formed developers on GitHub (we're not), you're just overcomplicating everything.

**Comment by rene78** [comment]
Something more user-friendly would need a back-end. Too lazy to write and too stingy to host that. Lots of converter websites on the Internet already, anyway. 

Alternatively a locally installable software can be written, e.g. with Electron. Looking forward to see your implementation 👍
